print("tool 691 is really cool")
print("tool 69 is really cool")
print("tool 69 is really cool")
print("tool 69 is really cool")
print("tool 69 is really cool")
print("tool 69 is really cool")
print("tool 69 is really cool")
